services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-server:
    image: senyoudev/service-discovery:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  apigw:
    image: senyoudev/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  auth:
    image: senyoudev/auth:latest
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - postgres
      - rabbitmq
      - zipkin


  project:
    image: senyoudev/project-service:latest
    container_name: project
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - postgres
      - rabbitmq
      - zipkin

  room:
    image: senyoudev/room-service:latest
    container_name: room-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - postgres
      - rabbitmq
      - zipkin

  upload:
    image: senyoudev/upload:latest
    container_name: upload
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: "development"
      CLOUD_NAME: "dfwmkpyfy"
      API_KEY: "846827645565756"
      API_SECRET: "ACMbZRBlpW5BiNzmNIo7tQlyiG8"
      UPLOAD_PRESET: "wafkbnld"
      ZIPKIN_ENDPOINT: "http://zipkin:9411"
      EUREKA_PORT: "8761"
      HOSTNAME: "docker_upload"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "eureka-server"
    networks:
      - spring
    depends_on:
      - eureka-server
      - rabbitmq
      - zipkin

  notification:
    image: senyoudev/notification:latest
    container_name: notification
    ports:
      - "3001:3001"
    environment:
      PORT: "3001"
      NODE_ENV: "docker_development"
      ZIPKIN_ENDPOINT: "http://zipkin:9411"
      EUREKA_PORT: "8761"
      HOSTNAME: "docker_notification"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "eureka-server"
      EXCHANGE: "internal.exchange"
      QUEUE: "notification.queue"
      ROUTING_KEY: "internal.notification.routing-key"
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - postgres
      - rabbitmq
      - zipkin

  task:
    image: senyoudev/task:latest
    container_name: task
    ports:
      - "3002:3002"
    environment:
      PORT: "3002"
      NODE_ENV: "docker_development"
      ZIPKIN_ENDPOINT: "http://zipkin:9411"
      EUREKA_PORT: "8761"
      HOSTNAME: "docker_task"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "eureka-server"
      CONNECTION_URL: "mongodb+srv://oditcontact:i5CI1Y7Lg1O0SCTZ@cluster0.vxilctb.mongodb.net"

    networks:
      - spring
    depends_on:
      - eureka-server
      - rabbitmq
      - zipkin
  feedback:
    image: senyoudev/feedback:latest
    container_name: feedback
    ports:
      - "3003:3003"
    environment:
      PORT: "3003"
      NODE_ENV: "docker_development"
      ZIPKIN_ENDPOINT: "http://zipkin:9411"
      EUREKA_PORT: "8761"
      HOSTNAME: "docker_feedback"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "eureka-server"
      CONNECTION_URL: "mongodb+srv://oditcontact:i5CI1Y7Lg1O0SCTZ@cluster0.vxilctb.mongodb.net"

    networks:
      - spring
    depends_on:
      - eureka-server
      - rabbitmq
      - zipkin

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge


volumes:
  postgres:
  pgadmin: