apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: senyoudev/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          envFrom:
            - configMapRef:
                name: notification-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification