server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**
        - id: users
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: project
          uri: lb://project
          predicates:
            - Path=/api/v1/projects/**, /api/v1/projectmembers/**, /api/v1/invitations/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true