server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**
        - id: users
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: project
          uri: lb://project
          predicates:
            - Path=/api/v1/projects/**, /api/v1/projectmembers/**, /api/v1/invitations/**,/api/v1/admin/Projects/**
          filters:
            - AuthenticationFilter
        - id: upload
          uri: lb://upload
          predicates:
            - Path=/api/v1/files/**
          filters:
            - AuthenticationFilter
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true