server:
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: project
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/projects
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    exchanges:
      internal: internal.exchange
    queues:
      notification: notification.queue
    routing-keys:
      internal-notification: internal.notification.routing-key
    host: rabbitmq
    port: 5672
Eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
springdoc:
  swagger-ui:
    enabled: true
    persist-authorization: true
  enable-spring-security: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans